<table style="outline: none; border-collapse: collapse; border-spacing: 0; table-layout: auto!important; margin: 0; padding: 0;" border="0" width="100%" cellspacing="0" cellpadding="0" bgcolor="#e5e5e5">
	<tbody>
		<tr>
			<td>
				<center>
					<table style="outline: none; border-collapse: collapse; border-spacing: 0; table-layout: fixed; width: 600px; min-width: 600px; margin: 0 auto; padding: 0;" border="0" width="600" cellspacing="0" cellpadding="0" align="center" bgcolor="#F4F4F4">
						<tbody>
							<tr>
								<td style="outline: none; width: 600px; min-width: 600px; margin: 0; padding: 0;" align="left" valign="top" width="600">
									<table style="outline: none; border-collapse: collapse; border-spacing: 0; table-layout: fixed; width: 100%; margin: 0; padding: 0;" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff">
										<tbody>
											<tr>
												<td style="text-align: center; color: #000; font-family: FreightSans Pro,Segoe UI,SanFrancisco Display,Arial,sans-serif; font-size: 26px; outline: none; width: 100%; margin: 0; padding: 20px 20px 0 20px;letter-spacing:1.2px;background: #2f2d39;" align="left" valign="top" bgcolor="#000">
													<div style="font-size:34px;font-style:normal;font-weight:normal;letter-spacing:1px;line-height:130%;text-align:left;color:#000fff">
                                                    <img src="https://viden.mobiup.io/assets/img/letters.png" width="100%" alt="">
                                                   </div>
                                                </td>
											</tr>
                                            <tr>
												<td style="text-align: center; color: #000; font-family: FreightSans Pro,Segoe UI,SanFrancisco Display,Arial,sans-serif; font-size: 26px; outline: none; width: 100%; margin: 0; padding: 30px 0 20px 20px;letter-spacing:1.2px;background: #2f2d39;" align="left" valign="top" bgcolor="#000"><div style="font-size:28px;font-style:normal;font-weight:normal;letter-spacing:1px;line-height:130%;text-align:left;color:#fff">
                                                    Inscrição na Lista de Prioridade
												</div></td>
											</tr>
											<tr>
												<td style="padding: 40px 20px 0 20px; word-break: break-word;font-family: Segoe UI,SanFrancisco Display,Arial,sans-serif; font-size: 16px; line-height: 150%; color: #333;text-align:center;">
													<div style="font-size:26px;font-style:normal;font-weight:normal;letter-spacing:1px;line-height:130%;text-align:left;color:#2f2d39">
                                                        Olá, <?=$this->name?>
                                                       <br> 
                                                      </div>
												</td>
											</tr>
                                            <tr>
												<td style="padding: 40px 20px 0 20px; word-break: break-word;font-family: Segoe UI,SanFrancisco Display,Arial,sans-serif; font-size: 16px; line-height: 150%; color: #333;text-align:center;">
													<div style="font-family:Helvetica;font-style:normal;font-weight:normal;letter-spacing:1px;line-height:130%;text-align:left;color:#000">
                                                        Sua inscrição na <strong>Lista de Prioridade (WL)</strong> para lançamento da Coleção Mergulho na WEB3 foi confirmada com sucesso!
                                                      </div>
												</td>
											</tr>
											<tr>
												<td style="padding: 40px 20px 0 20px; word-break: break-word;font-family: Segoe UI,SanFrancisco Display,Arial,sans-serif; font-size: 16px; line-height: 150%; color: #333;text-align:center;">
													<div style="font-family:Helvetica;font-style:normal;font-weight:normal;letter-spacing:1px;line-height:130%;text-align:left;color:#000">
                                                        Essa foi a carteira cadastrada na <strong>Lista de Prioridade:</strong>
                                                      </div>
												</td>
											</tr>
											<tr>
                                                <td style="text-align: center; font-size: 0px; padding: 40px 60px 40px 60px; word-break: break-word;" align="left">
                                                    <div style="font-weight:700; font-family: FreightSans Pro,Segoe UI,SanFrancisco Display,Arial,sans-serif; font-size: 16px; line-height: 150%; color: #000;padding:16px;background-color: #f5f5f5;border-radius:10px;">
                                                        <?=$this->wallet?>
                                                    </div>
                                                </td>
                                            </tr>
											<tr>
                                                <td style="text-align: center; font-size: 0px; padding: 0; word-break: break-word;border-top:3px solid #000;border-bottom:3px solid #000;" align="left">
                                                    <img src="https://viden.mobiup.io/assets/img/bg-meta.jpg" width="100%">
                                                </td>
                                            </tr>
                                            <tr>
												<td style="padding: 40px 20px 40px 20px; word-break: break-word;font-family: Segoe UI,SanFrancisco Display,Arial,sans-serif; font-size: 16px; line-height: 150%; color: #333;text-align:center;">
													<div style="font-family:Helvetica;font-style:normal;font-weight:normal;letter-spacing:1px;line-height:130%;text-align:left;color:#000">
                                                        Mensagem gerada automaticamente, não é necessário respondê-la.
                                                       <br> 
                                                       <br> 
                                                      </div>
												</td>
											</tr>
											<tr>
                                                
												<td style="font-family: Segoe UI,SanFrancisco Display,Arial,sans-serif;outline:none;width:100%;margin:0;padding:55px 20px;font-size: 16px;border-top:1px solid #e5e5e5;" align="left" valign="center" bgcolor="#F4F4F4">
													<div style="display:inline-block;width:45%;font-family:Helvetica;font-style:normal;font-weight:normal;letter-spacing:1px;line-height:130%;text-align:left;color:#000">Até mais,<br><strong>Equipe Mergulho na WEB3</strong></div>
                                                    <div style="display:inline-block;width:50%;font-family:Helvetica;font-style:normal;font-weight:normal;letter-spacing:1px;line-height:130%;text-align:right;color:#000">
                                                        <a href="https://mobiup.com.br" targtet="_blank"><img src="https://viden.mobiup.io/assets/img/MobiUp-Logo-2-sem-fundo.png" width="160"></a>
                                                    </div>
												</td>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</center>
			</td>
		</tr>
	</tbody>
</table>