<?php
    header('Content-Type: application/json');

    $returnData = [
        'data' => [
            'code'   => $this->exception->getCode(),
            'file' => $this->exception->getFile(),
            'line' => $this->exception->getLine(),
            'reason' => $this->escapeHtml($this->exception->getMessage()),
            'trace_error' => $this->escapeHtml($this->exception->getTraceAsString())
        ],
        'maintenance' => false,
        'request_time' => (new \DateTime())->format('Y-m-d H:i:s.u')
    ];

    echo json_encode($returnData);
?>
